import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";
import { poppins } from "@/lib/fonts";
import { Toaster } from "sonner";
import Providers from "@/app/providers";

export const metadata: Metadata = {
  title: "Home | Food",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Script id="browser-storage-bridge" strategy="beforeInteractive">
        {`try{window.browserStorage=window.localStorage}catch{window.browserStorage={getItem:function(){return null},setItem:function(){},removeItem:function(){},clear:function(){},key:function(){return null},length:0}}`}
      </Script>
      <body className={poppins.className}>
  <Providers>
    <Toaster position="top-right" richColors />

    {children}
  </Providers>
</body>
    </html>
  );
}
